//
//   Automatically generated by the ThaiLinh compiler, do not modify.
//
//  GirlModel.swift
//  Swift version 4.2
//
//  Created by thailinh on 2021/07/28).
//  Copyright © 2021/07/28 thailinh. All rights reserved.
//

import Foundation

public class GirlModel {

	public var likeCounts 	: Int64! 
	public var createdAt 	: String! 
	public var status 	: Int64! 
	public var page_count 	: Int64! 
	public var views 	: Int64! 
	public var type 	: String! 
	public var page 	: Int64! 
	public var publishedAt 	: String! 
	public var category 	: String! 
	public var _id 	: String! 
	public var images 	: [String]! 
	public var total_counts 	: Int64! 
	public var desc 	: String! 
	public var title 	: String! 
	public var stars 	: Int64! 
	public var url 	: String! 
	public var author 	: String! 
	public var ctldata 	: [GirlModel]! 

	public convenience init(likeCounts: Int64!, 
							createdAt: String!, 
							status: Int64!, 
							page_count: Int64!, 
							views: Int64!, 
							type: String!, 
							page: Int64!, 
							publishedAt: String!, 
							category: String!, 
							_id: String!, 
							images: [String]!, 
							total_counts: Int64!, 
							desc: String!, 
							title: String!, 
							stars: Int64!, 
							url: String!, 
							author: String!, 
							ctldata: [GirlModel]!) {

		self.init()
		self.likeCounts = likeCounts
		self.createdAt = createdAt
		self.status = status
		self.page_count = page_count
		self.views = views
		self.type = type
		self.page = page
		self.publishedAt = publishedAt
		self.category = category
		self._id = _id
		self.images = images
		self.total_counts = total_counts
		self.desc = desc
		self.title = title
		self.stars = stars
		self.url = url
		self.author = author
		self.ctldata = ctldata
	}

}

